<a href="https://colab.research.google.com/github/hewan00/eda_assignment/blob/main/eda_assiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
! git clone https://github.com/ds3001f25/eda_assignment.git
!ls eda_assignment

fatal: destination path 'eda_assignment' already exists and is not an empty directory.
assignment.ipynb  data	README.md

In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [33]:
df_airbnb = pd.read_csv('./eda_assignment/data/airbnb_hw.csv', low_memory=False)
df_airbnb.head()

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,6/26/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
4,500,6/26/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0

In [34]:
df_rigs = pd.read_csv('./eda_assignment/data/drilling_rigs.csv', low_memory=False)
df_rigs.head()

,Month,"Crude Oil and Natural Gas Rotary Rigs in Operation, Onshore (Number of Rigs)","Crude Oil and Natural Gas Rotary Rigs in Operation, Offshore (Number of Rigs)","Crude Oil Rotary Rigs in Operation, Total (Number of Rigs)","Natural Gas Rotary Rigs in Operation, Total (Number of Rigs)","Crude Oil and Natural Gas Rotary Rigs in Operation, Horizontal Trajectory (Number of Rigs)","Crude Oil and Natural Gas Rotary Rigs in Operation, Directional Trajectory (Number of Rigs)","Crude Oil and Natural Gas Rotary Rigs in Operation, Vertical Trajectory (Number of Rigs)","Crude Oil and Natural Gas Rotary Rigs in Operation, Total (Number of Rigs)",Active Well Service Rig Count (Number of Rigs)
0,1973 January,1120,99,Not Available,Not Available,Not Available,Not Available,Not Available,1219,1549
1,1973 February,1037,89,Not Available,Not Available,Not Available,Not Available,Not Available,1126,1677
2,1973 March,959,90,Not Available,Not Available,Not Available,Not Available,Not Available,1049,1805
3,1973 April,914,79,Not Available,Not Available,Not Available,Not Available,Not Available,993,1898
4,1973 May,974,72,Not Available,Not Available,Not Available,Not Available,Not Available,1046,1991

In [35]:
# --- Q2 Airbnb Data ---
df_airbnb = pd.read_csv('./eda_assignment/data/airbnb_hw.csv', low_memory=False)

# background info
print("Shape of Airbnb DF:", df_airbnb.shape)
print("Cols:", df_airbnb.columns.tolist())
df_airbnb.head()

Shape of Airbnb DF: (30478, 13)
Cols: ['Host Id', 'Host Since', 'Name', 'Neighbourhood ', 'Property Type', 'Review Scores Rating (bin)', 'Room Type', 'Zipcode', 'Beds', 'Number of Records', 'Number Of Reviews', 'Price', 'Review Scores Rating']

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,6/26/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
4,500,6/26/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0

In [36]:
pd.crosstab(df_airbnb['Room Type'], df_airbnb['Property Type'])

Property Type,Apartment,Bed & Breakfast,Boat,Bungalow,Cabin,Camper/RV,Castle,Chalet,Condominium,Dorm,House,Hut,Lighthouse,Loft,Other,Tent,Townhouse,Treehouse,Villa
Room Type,,,,,,,,,,,,,,,,,,,
Entire home/apt,15669,13,7,4,1,6,0,0,72,4,752,0,1,392,14,0,83,0,4
Private room,10748,155,1,0,1,1,1,1,22,16,1258,2,0,312,29,4,52,1,4
Shared room,685,12,0,0,0,0,0,0,0,11,80,0,0,49,4,0,1,3,0

In [37]:
# Convert price to numeric (some commas/strings)
df_airbnb['price'] = df_airbnb['price'].str.replace(',','')
df_airbnb['price'] = pd.to_numeric(df_airbnb['price'], errors='coerse')  # #error

# histogram
df_airbnb['price'].plot.hist(bins=40, title="Price Histogram")
plt.show()

# boxplot
df_airbnb['price'].plot.box(title="Price Box")
plt.show()

KeyError: 'price'

Prices are super skewed (lots of cheap rentals, few very expensive ones).
Boxplot shows many outliers at high prices.

In [ ]:
df_airbnb['price_log'] = np.log(df_airbnb['price']+1)  # +1 to avoid log(0)

df_airbnb['price_log'].plot.hist(bins=40, title="Log Price Histogram")
plt.show(). ##Log transformation compresses big numbers → histogram looks more “normal.”

In [ ]:
sns.scatterplot(data=df_airbnb, x='Beds', y='price_log')
plt.title("Price vs Beds (log)")
plt.show()

df_airbnb.groupby('Beds')['price_log'].describe()

1-2 beds show lots of variability.
More beds → higher mean price, but weird spikes exist.

In [ ]:
sns.scatterplot(data=df_airbnb, x='Beds', y='price_log', hue='Room Type', style='Property Type')
plt.title("Price vs Beds by Room/Property")
plt.show()

df_airbnb.groupby(['Room Type','Property Type'])['price_log'].describe()
#Entire home/apartment usually highest price.
#“Other” property type has highest mean & SD.
#Median seems better than mean for central tendency because of extreme outliers.

In [ ]:
df_rigs = pd.read_csv('./eda_assignment/data/drilling_rigs.csv', low_memory=False)
df_rigs.head()
df_rigs['time'] = pd.to_datetime(df_rigs['Month'], format='mixed')
df_rigs['time'] = pd.to_datetime(df_rigs['Month'], format='mixed')

Overall trend decreasing.
Some spikes & drops.

In [ ]:
df_rigs['Active Well Service Rig Count (Number of Rigs)'] = pd.to_numeric(df_rigs['Active Well Service Rig Count (Number of Rigs)'], errors='coerce')
df_rigs['diff'] = df_rigs['Active Well Service Rig Count (Number of Rigs)'].diff()

sns.lineplot(data=df_rigs, x='time', y='diff')
plt.title("Change in Rig Count Over Time")
plt.show()

In [ ]:
df_rigs_melt = pd.melt(df_rigs, id_vars='time',
                       value_vars=['Crude Oil and Natural Gas Rotary Rigs in Operation, Onshore (Number of Rigs)',
                                   'Crude Oil and Natural Gas Rotary Rigs in Operation, Offshore (Number of Rigs)'],
                       var_name='Rig Type', value_name='Count')

sns.lineplot(data=df_rigs_melt, x='time', y='Count', hue='Rig Type')
plt.title("Onshore vs Offshore Rigs")
plt.show()

Onshore usually more rigs than offshore.
Both fluctuate together over time.